### ISSUE TITLE
Issue on running destinGrid

### ISSUE THREAD

**Issue by JingxinGuo** [urrutiag/destin#1]
Hello,
 I met the error when running destinGrid function like this:
Cannot use := to add columns to a null data.table (no columns), currently. You can use := to add (empty) columns to a 0-row data.table (1 or more empty columns), though. 

Here are some codes I run:
> assay(rse)[1:5,1:5]
5 x 5 sparse Matrix of class "dgTMatrix"
              
[1,] . . . . .
[2,] . . . . .
[3,] . . . . .
[4,] . . . . .
[5,] . . . . .
> colData(rse)
DataFrame with 959 rows and 2 columns
                       V1 cellSumPostQC
                 <factor>     <numeric>
1     singles-GM-1          3890
2    singles-GM-12          3073
3    singles-GM-23          1532
4    singles-GM-34          3708
5    singles-GM-56          4308
...                   ...           ...
955 singles-TF1-92          5867
956 singles-TF1-93          2346
957 singles-TF1-94          5320
958 singles-TF1-95          4620
959 singles-TF1-96          5483
> rowRanges(rse)
GRanges object with 117334 ranges and 4 metadata columns:
           seqnames               ranges strand |    DHSsum distanceToTSS
              <Rle>            <IRanges>  <Rle> | <numeric>     <numeric>
       [1]     chr1     [237589, 238087]      * | 18.368897         -8814
       [2]     chr1     [713901, 714399]      * | 40.333352          -262
       [3]     chr1     [752504, 753002]      * | 16.674338          -248
       [4]     chr1     [762584, 763082]      * | 39.597792           318
       [5]     chr1     [778070, 778568]      * |  3.116069         15081
       ...      ...                  ...    ... .       ...           ...
  [117330]    chr22 [51125644, 51126142]      * |  9.302069          4147
  [117331]    chr22 [51143694, 51144192]      * | 11.692425        -13903
  [117332]    chr22 [51171705, 51172203]      * | 16.563892          4862
  [117333]    chr22 [51195484, 51195982]      * | 13.504730           107
  [117334]    chr22 [51221804, 51222302]      * | 29.445625           287
                   feature         region
               <character>    <character>
       [1] ENSG00000241670 distal element
       [2] ENSG00000237491       promoter
       [3] ENSG00000177757       promoter
       [4] ENSG00000225880       promoter
       [5] ENSG00000228794 distal element
       ...             ...            ...
  [117330] ENSG00000206841 distal element
  [117331] ENSG00000206841 distal element
  [117332] ENSG00000225929 distal element
  [117333] ENSG00000184319       promoter
  [117334] ENSG00000079974       promoter
  -------
  seqinfo: 22 sequences from an unspecified genome; no seqlengths
## Determine number of clusters
> rse = doQC(rse, regionSumCutoff = 3, cellSumCutoffSDs = 5)
> set.seed(10)
> nClustersMax = 20
> clusterEst = estimateNClusters(rse, nClustersMax = nClustersMax)
Clustering k = 1,2,..., K.max (= 20): .. done
Bootstrapping, b = 1,2,..., B (= 500)  [one "." per sample]:
.................................................. 50 
.................................................. 100 
.................................................. 150 
.................................................. 200 
.................................................. 250 
.................................................. 300 
.................................................. 350 
.................................................. 400 
.................................................. 450 
.................................................. 500 
There were 35 warnings (use warnings() to see them)
> pdf("./plotNClusters.pdf",width=8,height=8)
> plotNClusters(clusterEst)
Warning message:
Removed 1 rows containing missing values (geom_point). 
> dev.off()
null device 
          1 
> nCores = 3
> nClusters = clusterEst$nClustersList$logLikeElbow
> PCrange = 8:12
> TSSWeightsList = list(c(1,1),c(1,2))
> DHSWeightsList = list(c(1,1), c(1,3))
> results = destinGrid (rse, sampleName, 
+                  PCrange = PCrange,
+                  TSSWeightsList = TSSWeightsList,
+                  DHSWeightsList = DHSWeightsList,
+                  nClusters = nClusters)
Error in data.frame(cellID = rse$cellID, cluster = kfit$cluster) : 
  arguments imply differing number of rows: 0, 959
Error in data.frame(cellID = rse$cellID, cluster = kfit$cluster) : 
  arguments imply differing number of rows: 0, 959
Error in data.frame(cellID = rse$cellID, cluster = kfit$cluster) : 
  arguments imply differing number of rows: 0, 959
Error in data.frame(cellID = rse$cellID, cluster = kfit$cluster) : 
  arguments imply differing number of rows: 0, 959
Error in `[<-.data.table`(x, j = name, value = value) : 
  Cannot use := to add columns to a null data.table (no columns), currently. You can use := to add (empty) columns to a 0-row data.table (1 or more empty columns), though.

Many thanks for your help!

**Comment by urrutiag** [comment]
Hi, thanks for your interest in Destin.

Destin is looking for the cellID column in colData(rse).   If you rename
the column named V1 as cellID, it should solve the problem.  I will add a
check in destinGrid to identify this issue going forward.  Please let me
know if you have any other issues.

Thanks,
Gene

**Comment by JingxinGuo** [comment]
Hi, many thanks for your help! 

I met a new problem? When I run destinGrid like this:
nClusters = 4
> PCrange = 3:10 
> sampleName = "zhang"
> results = destinGrid(rse, sampleName,
+                        PCrange = PCrange,
+                        nClusters = nClusters,
+                        nCores = nCores)
Error in `[<-.data.table`(x, j = name, value = value) : 
  Cannot use := to add columns to a null data.table (no columns), currently. You can use := to add (empty) columns to a 0-row data.table (1 or more empty columns), though.

What the problem is?

**Comment by urrutiag** [comment]
Hi, I will need more information in order to identify the problem.  Is it
possible to save and send me your data so that I can reproduce the issue?
Otherwise, please print and send me the results of previous steps so I can
understand more fully.
Thanks,
Gene

**Comment by JingxinGuo** [comment]
Hi, here is all my steps and results, the error happened when I run function: destinGrid

data10xDir = "./Destin/10x_matrix"
rse = createRSEfrom10xMatrix(data10xDir)
colData(rse)
DataFrame with 1047 rows and 1 column
#                V1
#          <factor>
# 1    ACTTTCTAATCA
# 2    GAGAGAAAACCT
# 3    TACGGCTGTTAT
# 4    GACGCGTAAGTG
# 5    GAAAGGACTGCA
# ...           ...
# 1043 GTTCTTCCTAGT
# 1044 ATCCGTTCAACG
# 1045 CCGACTAAGAAT
# 1046 AAGCCTGGGGGC
# 1047 CAGCTGGTGATG

colnames(colData(rse)) <- c("cellID")
rowRanges(rse)
# GRanges object with 136475 ranges and 0 metadata columns:
#            seqnames                 ranges strand
#               <Rle>              <IRanges>  <Rle>
#        [1]     chr2 [149639224, 149639496]      *
#        [2]     chr8 [100508027, 100508251]      *
#        [3]    chr22 [ 22089734,  22090705]      *
#        [4]     chr3 [ 28282796,  28283506]      *
#        [5]     chr5 [154007199, 154007946]      *
#        ...      ...                    ...    ...
#   [136471]    chr15   [76102342, 76102770]      *
#   [136472]    chr15   [76546242, 76546617]      *
#   [136473]    chr15   [77097573, 77097864]      *
#   [136474]    chr15   [78177410, 78177781]      *
#   [136475]    chr15   [79471519, 79471726]      *
#   -------
#   seqinfo: 32 sequences from an unspecified genome; no seqlengths

assay(rse)[1:20,1:20]
# 20 x 20 sparse Matrix of class "dgTMatrix"
                                             
#  [1,] 1 1 1 . . 1 1 . . 1 . 1 . . . 1 1 1 . .
#  [2,] 1 1 . . . 1 . 1 . . . 1 . 1 . 1 . . . .
#  [3,] . . . . . . . . . . . . . . . . . . . .
#  [4,] . . . . . . . . . . . . . . . . 1 . 1 .
#  [5,] . . . . . . . . . . . . . . 1 . . . . .
#  [6,] . . . . . . . . . . . . . . . . . . . .
#  [7,] . . . . . . . . . . . . . . . . . . . .
#  [8,] . . . . . . . . . . . . . . . . . . . .
#  [9,] . . . . . . . . . . . . . . . . . . . .
# [10,] . . . . . . . . . . . . . . . . . . . .

## Annotate regions
sampleName = "zk"
yourPathToDestinRepo="./Destin/"
outDir = file.path(yourPathToDestinRepo)
model = "hg19"
rse = annotateRSE(rse, model)
# There were 50 or more warnings (use warnings() to see the first 50)
warnings()
# Warning messages:
# 1: In annotatePeakInBatch(rowRanges(rse), AnnotationData = annoFile,  ... :
#   not all the seqnames of myPeakList is 
#                     in the AnnotationData.
# 2: In FUN(extractROWS(unlisted_X, IRanges(X_elt_start[i],  ... :
#   not all the seqnames of myPeakList is 
#                     in the AnnotationData.
# 3: In .Seqinfo.mergexy(x, y) :
#   Each of the 2 combined objects has sequence levels not in the other:
#   - in 'x': chr17_gl000205_random, chrUn_gl000229, chr17_gl000204_random, chrUn_gl000228, chrUn_gl000220, chr4_gl000193_random, chr11_gl000202_random, chr1_gl000192_random
#   - in 'y': GL000191.1, GL000192.1, GL000193.1, GL000194.1, GL000195.1, GL000197.1, GL000199.1, GL000200.1, GL000201.1, GL000204.1, GL000205.1, GL000209.1, GL000211.1, GL000212.1, GL000213.1, GL000214.1, GL000216.1, GL000218.1, GL000219.1, GL000220.1, GL000221.1, GL000222.1, GL000223.1, GL000224.1, GL000225.1, GL000227.1, GL000228.1, GL000229.1, GL000230.1, GL000233.1, GL000236.1, GL000237.1, GL000238.1, GL000239.1, GL000240.1, GL000241.1, GL000242.1, GL000243.1, GL000247.1, HSCHR17_1, HSCHR6_MHC_APD, HSCHR6_MHC_COX, HSCHR6_MHC_DBB, HSCHR6_MHC_MANN, HSCHR6_MHC_MCF, HSCHR6_MHC_QBL, HSCHR6_MHC_SSTO, chrM
#   Make sure to always combine/compare objects based on the same reference
#   genome (use suppressWarnings() to suppress this warning).
# 4: In FUN(extractROWS(unlisted_X, IRanges(X_elt_start[i],  ... :
#   not all the seqnames of myPeakList is 
#                     in the AnnotationData.
# 5: In .Seqinfo.mergexy(x, y) :
#   Each of the 2 combined objects has sequence levels not in the other:
#   - in 'x': chr17_gl000205_random, chrUn_gl000229, chr17_gl000204_random, chrUn_gl000228, chrUn_gl000220, chr4_gl000193_random, chr11_gl000202_random, chr1_gl000192_random
#   - in 'y': GL000191.1, GL000192.1, GL000193.1, GL000194.1, GL000195.1, GL000197.1, GL000199.1, GL000200.1, GL000201.1, GL000204.1, GL000205.1, GL000209.1, GL000211.1, GL000212.1, GL000213.1, GL000214.1, GL000216.1, GL000218.1, GL000219.1, GL000220.1, GL000221.1, GL000222.1, GL000223.1, GL000224.1, GL000225.1, GL000227.1, GL000228.1, GL000229.1, GL000230.1, GL000233.1, GL000236.1, GL000237.1, GL000238.1, GL000239.1, GL000240.1, GL000241.1, GL000242.1, GL000243.1, GL000247.1, HSCHR17_1, HSCHR6_MHC_APD, HSCHR6_MHC_COX, HSCHR6_MHC_DBB, HSCHR6_MHC_MANN, HSCHR6_MHC_MCF, HSCHR6_MHC_QBL, HSCHR6_MHC_SSTO, chrM
#   Make sure to always combine/compare objects based on the same reference
#   genome (use suppressWarnings() to suppress this warning).
# 6: In FUN(extractROWS(unlisted_X, IRanges(X_elt_start[i],  ... :
#   not all the seqnames of myPeakList is 
#                     in the AnnotationData.
# 7: In .Seqinfo.mergexy(x, y) :
#   Each of the 2 combined objects has sequence levels not in the other:
#   - in 'x': chr17_gl000205_random, chrUn_gl000229, chr17_gl000204_random, chrUn_gl000228, chrUn_gl000220, chr4_gl000193_random, chr11_gl000202_random, chr1_gl000192_random
#   - in 'y': GL000191.1, GL000192.1, GL000193.1, GL000194.1, GL000195.1, GL000197.1, GL000199.1, GL000200.1, GL000201.1, GL000204.1, GL000205.1, GL000209.1, GL000211.1, GL000212.1, GL000213.1, GL000214.1, GL000216.1, GL000218.1, GL000219.1, GL000220.1, GL000221.1, GL000222.1, GL000223.1, GL000224.1, GL000225.1, GL000227.1, GL000228.1, GL000229.1, GL000230.1, GL000233.1, GL000236.1, GL000237.1, GL000238.1, GL000239.1, GL000240.1, GL000241.1, GL000242.1, GL000243.1, GL000247.1, HSCHR17_1, HSCHR6_MHC_APD, HSCHR6_MHC_COX, HSCHR6_MHC_DBB, HSCHR6_MHC_MANN, HSCHR6_MHC_MCF, HSCHR6_MHC_QBL, HSCHR6_MHC_SSTO, chrM
#   Make sure to always combine/compare objects based on the same reference
#   genome (use suppressWarnings() to suppress this warning).
# 8: In FUN(extractROWS(unlisted_X, IRanges(X_elt_start[i],  ... :
#   not all the seqnames of myPeakList is 
#                     in the AnnotationData.
# 9: In .Seqinfo.mergexy(x, y) :
#   Each of the 2 combined objects has sequence levels not in the other:
#   - in 'x': chr17_gl000205_random, chrUn_gl000229, chr17_gl000204_random, chrUn_gl000228, chrUn_gl000220, chr4_gl000193_random, chr11_gl000202_random, chr1_gl000192_random
#   - in 'y': GL000191.1, GL000192.1, GL000193.1, GL000194.1, GL000195.1, GL000197.1, GL000199.1, GL000200.1, GL000201.1, GL000204.1, GL000205.1, GL000209.1, GL000211.1, GL000212.1, GL000213.1, GL000214.1, GL000216.1, GL000218.1, GL000219.1, GL000220.1, GL000221.1, GL000222.1, GL000223.1, GL000224.1, GL000225.1, GL000227.1, GL000228.1, GL000229.1, GL000230.1, GL000233.1, GL000236.1, GL000237.1, GL000238.1, GL000239.1, GL000240.1, GL000241.1, GL000242.1, GL000243.1, GL000247.1, HSCHR17_1, HSCHR6_MHC_APD, HSCHR6_MHC_COX, HSCHR6_MHC_DBB, HSCHR6_MHC_MANN, HSCHR6_MHC_MCF, HSCHR6_MHC_QBL, HSCHR6_MHC_SSTO, chrM
#   Make sure to always combine/compare objects based on the same reference
#   genome (use suppressWarnings() to suppress this warning).
# 10: In FUN(extractROWS(unlisted_X, IRanges(X_elt_start[i],  ... :
#   not all the seqnames of myPeakList is 
#                     in the AnnotationData.
# 11: In .Seqinfo.mergexy(x, y) :
#   Each of the 2 combined objects has sequence levels not in the other:
#   - in 'x': chr17_gl000205_random, chrUn_gl000229, chr17_gl000204_random, chrUn_gl000228, chrUn_gl000220, chr4_gl000193_random, chr11_gl000202_random, chr1_gl000192_random
#   - in 'y': GL000191.1, GL000192.1, GL000193.1, GL000194.1, GL000195.1, GL000197.1, GL000199.1, GL000200.1, GL000201.1, GL000204.1, GL000205.1, GL000209.1, GL000211.1, GL000212.1, GL000213.1, GL000214.1, GL000216.1, GL000218.1, GL000219.1, GL000220.1, GL000221.1, GL000222.1, GL000223.1, GL000224.1, GL000225.1, GL000227.1, GL000228.1, GL000229.1, GL000230.1, GL000233.1, GL000236.1, GL000237.1, GL000238.1, GL000239.1, GL000240.1, GL000241.1, GL000242.1, GL000243.1, GL000247.1, HSCHR17_1, HSCHR6_MHC_APD, HSCHR6_MHC_COX, HSCHR6_MHC_DBB, HSCHR6_MHC_MANN, HSCHR6_MHC_MCF, HSCHR6_MHC_QBL, HSCHR6_MHC_SSTO, chrM
#   Make sure to always combine/compare objects based on the same reference
#   genome (use suppressWarnings() to suppress this warning).
# 12: In FUN(extractROWS(unlisted_X, IRanges(X_elt_start[i],  ... :
#   not all the seqnames of myPeakList is 
#                     in the AnnotationData.
# 13: In .Seqinfo.mergexy(x, y) :
#   Each of the 2 combined objects has sequence levels not in the other:
#   - in 'x': chr17_gl000205_random, chrUn_gl000229, chr17_gl000204_random, chrUn_gl000228, chrUn_gl000220, chr4_gl000193_random, chr11_gl000202_random, chr1_gl000192_random
#   - in 'y': GL000191.1, GL000192.1, GL000193.1, GL000194.1, GL000195.1, GL000197.1, GL000199.1, GL000200.1, GL000201.1, GL000204.1, GL000205.1, GL000209.1, GL000211.1, GL000212.1, GL000213.1, GL000214.1, GL000216.1, GL000218.1, GL000219.1, GL000220.1, GL000221.1, GL000222.1, GL000223.1, GL000224.1, GL000225.1, GL000227.1, GL000228.1, GL000229.1, GL000230.1, GL000233.1, GL000236.1, GL000237.1, GL000238.1, GL000239.1, GL000240.1, GL000241.1, GL000242.1, GL000243.1, GL000247.1, HSCHR17_1, HSCHR6_MHC_APD, HSCHR6_MHC_COX, HSCHR6_MHC_DBB, HSCHR6_MHC_MANN, HSCHR6_MHC_MCF, HSCHR6_MHC_QBL, HSCHR6_MHC_SSTO, chrM
#   Make sure to always combine/compare objects based on the same reference
#   genome (use suppressWarnings() to suppress this warning).
# 14: In FUN(extractROWS(unlisted_X, IRanges(X_elt_start[i],  ... :
#   not all the seqnames of myPeakList is 
#                     in the AnnotationData.
# 15: In .Seqinfo.mergexy(x, y) :
#   Each of the 2 combined objects has sequence levels not in the other:
#   - in 'x': chr17_gl000205_random, chrUn_gl000229, chr17_gl000204_random, chrUn_gl000228, chrUn_gl000220, chr4_gl000193_random, chr11_gl000202_random, chr1_gl000192_random
#   - in 'y': GL000191.1, GL000192.1, GL000193.1, GL000194.1, GL000195.1, GL000197.1, GL000199.1, GL000200.1, GL000201.1, GL000204.1, GL000205.1, GL000209.1, GL000211.1, GL000212.1, GL000213.1, GL000214.1, GL000216.1, GL000218.1, GL000219.1, GL000220.1, GL000221.1, GL000222.1, GL000223.1, GL000224.1, GL000225.1, GL000227.1, GL000228.1, GL000229.1, GL000230.1, GL000233.1, GL000236.1, GL000237.1, GL000238.1, GL000239.1, GL000240.1, GL000241.1, GL000242.1, GL000243.1, GL000247.1, HSCHR17_1, HSCHR6_MHC_APD, HSCHR6_MHC_COX, HSCHR6_MHC_DBB, HSCHR6_MHC_MANN, HSCHR6_MHC_MCF, HSCHR6_MHC_QBL, HSCHR6_MHC_SSTO, chrM
#   Make sure to always combine/compare objects based on the same reference
#   genome (use suppressWarnings() to suppress this warning).
# 16: In FUN(extractROWS(unlisted_X, IRanges(X_elt_start[i],  ... :
#   not all the seqnames of myPeakList is 
#                     in the AnnotationData.
# 17: In .Seqinfo.mergexy(x, y) :
#   Each of the 2 combined objects has sequence levels not in the other:
#   - in 'x': chr17_gl000205_random, chrUn_gl000229, chr17_gl000204_random, chrUn_gl000228, chrUn_gl000220, chr4_gl000193_random, chr11_gl000202_random, chr1_gl000192_random
#   - in 'y': GL000191.1, GL000192.1, GL000193.1, GL000194.1, GL000195.1, GL000197.1, GL000199.1, GL000200.1, GL000201.1, GL000204.1, GL000205.1, GL000209.1, GL000211.1, GL000212.1, GL000213.1, GL000214.1, GL000216.1, GL000218.1, GL000219.1, GL000220.1, GL000221.1, GL000222.1, GL000223.1, GL000224.1, GL000225.1, GL000227.1, GL000228.1, GL000229.1, GL000230.1, GL000233.1, GL000236.1, GL000237.1, GL000238.1, GL000239.1, GL000240.1, GL000241.1, GL000242.1, GL000243.1, GL000247.1, HSCHR17_1, HSCHR6_MHC_APD, HSCHR6_MHC_COX, HSCHR6_MHC_DBB, HSCHR6_MHC_MANN, HSCHR6_MHC_MCF, HSCHR6_MHC_QBL, HSCHR6_MHC_SSTO, chrM
#   Make sure to always combine/compare objects based on the same reference
#   genome (use suppressWarnings() to suppress this warning).
# 18: In FUN(extractROWS(unlisted_X, IRanges(X_elt_start[i],  ... :
#   not all the seqnames of myPeakList is 
#                     in the AnnotationData.
# 19: In .Seqinfo.mergexy(x, y) :
#   Each of the 2 combined objects has sequence levels not in the other:
#   - in 'x': chr17_gl000205_random, chrUn_gl000229, chr17_gl000204_random, chrUn_gl000228, chrUn_gl000220, chr4_gl000193_random, chr11_gl000202_random, chr1_gl000192_random
#   - in 'y': GL000191.1, GL000192.1, GL000193.1, GL000194.1, GL000195.1, GL000197.1, GL000199.1, GL000200.1, GL000201.1, GL000204.1, GL000205.1, GL000209.1, GL000211.1, GL000212.1, GL000213.1, GL000214.1, GL000216.1, GL000218.1, GL000219.1, GL000220.1, GL000221.1, GL000222.1, GL000223.1, GL000224.1, GL000225.1, GL000227.1, GL000228.1, GL000229.1, GL000230.1, GL000233.1, GL000236.1, GL000237.1, GL000238.1, GL000239.1, GL000240.1, GL000241.1, GL000242.1, GL000243.1, GL000247.1, HSCHR17_1, HSCHR6_MHC_APD, HSCHR6_MHC_COX, HSCHR6_MHC_DBB, HSCHR6_MHC_MANN, HSCHR6_MHC_MCF, HSCHR6_MHC_QBL, HSCHR6_MHC_SSTO, chrM
#   Make sure to always combine/compare objects based on the same reference
#   genome (use suppressWarnings() to suppress this warning).
# 20: In FUN(extractROWS(unlisted_X, IRanges(X_elt_start[i],  ... :
#   not all the seqnames of myPeakList is 
#                     in the AnnotationData.
# 21: In .Seqinfo.mergexy(x, y) :
#   Each of the 2 combined objects has sequence levels not in the other:
#   - in 'x': chr17_gl000205_random, chrUn_gl000229, chr17_gl000204_random, chrUn_gl000228, chrUn_gl000220, chr4_gl000193_random, chr11_gl000202_random, chr1_gl000192_random
#   - in 'y': GL000191.1, GL000192.1, GL000193.1, GL000194.1, GL000195.1, GL000197.1, GL000199.1, GL000200.1, GL000201.1, GL000204.1, GL000205.1, GL000209.1, GL000211.1, GL000212.1, GL000213.1, GL000214.1, GL000216.1, GL000218.1, GL000219.1, GL000220.1, GL000221.1, GL000222.1, GL000223.1, GL000224.1, GL000225.1, GL000227.1, GL000228.1, GL000229.1, GL000230.1, GL000233.1, GL000236.1, GL000237.1, GL000238.1, GL000239.1, GL000240.1, GL000241.1, GL000242.1, GL000243.1, GL000247.1, HSCHR17_1, HSCHR6_MHC_APD, HSCHR6_MHC_COX, HSCHR6_MHC_DBB, HSCHR6_MHC_MANN, HSCHR6_MHC_MCF, HSCHR6_MHC_QBL, HSCHR6_MHC_SSTO, chrM
#   Make sure to always combine/compare objects based on the same reference
#   genome (use suppressWarnings() to suppress this warning).
# 22: In FUN(extractROWS(unlisted_X, IRanges(X_elt_start[i],  ... :
#   not all the seqnames of myPeakList is 
#                     in the AnnotationData.
# 23: In .Seqinfo.mergexy(x, y) :
#   Each of the 2 combined objects has sequence levels not in the other:
#   - in 'x': chr17_gl000205_random, chrUn_gl000229, chr17_gl000204_random, chrUn_gl000228, chrUn_gl000220, chr4_gl000193_random, chr11_gl000202_random, chr1_gl000192_random
#   - in 'y': GL000191.1, GL000192.1, GL000193.1, GL000194.1, GL000195.1, GL000197.1, GL000199.1, GL000200.1, GL000201.1, GL000204.1, GL000205.1, GL000209.1, GL000211.1, GL000212.1, GL000213.1, GL000214.1, GL000216.1, GL000218.1, GL000219.1, GL000220.1, GL000221.1, GL000222.1, GL000223.1, GL000224.1, GL000225.1, GL000227.1, GL000228.1, GL000229.1, GL000230.1, GL000233.1, GL000236.1, GL000237.1, GL000238.1, GL000239.1, GL000240.1, GL000241.1, GL000242.1, GL000243.1, GL000247.1, HSCHR17_1, HSCHR6_MHC_APD, HSCHR6_MHC_COX, HSCHR6_MHC_DBB, HSCHR6_MHC_MANN, HSCHR6_MHC_MCF, HSCHR6_MHC_QBL, HSCHR6_MHC_SSTO, chrM
#   Make sure to always combine/compare objects based on the same reference
#   genome (use suppressWarnings() to suppress this warning).
# 24: In FUN(extractROWS(unlisted_X, IRanges(X_elt_start[i],  ... :
#   not all the seqnames of myPeakList is 
#                     in the AnnotationData.
# 25: In .Seqinfo.mergexy(x, y) :
#   Each of the 2 combined objects has sequence levels not in the other:
#   - in 'x': chr17_gl000205_random, chrUn_gl000229, chr17_gl000204_random, chrUn_gl000228, chrUn_gl000220, chr4_gl000193_random, chr11_gl000202_random, chr1_gl000192_random
#   - in 'y': GL000191.1, GL000192.1, GL000193.1, GL000194.1, GL000195.1, GL000197.1, GL000199.1, GL000200.1, GL000201.1, GL000204.1, GL000205.1, GL000209.1, GL000211.1, GL000212.1, GL000213.1, GL000214.1, GL000216.1, GL000218.1, GL000219.1, GL000220.1, GL000221.1, GL000222.1, GL000223.1, GL000224.1, GL000225.1, GL000227.1, GL000228.1, GL000229.1, GL000230.1, GL000233.1, GL000236.1, GL000237.1, GL000238.1, GL000239.1, GL000240.1, GL000241.1, GL000242.1, GL000243.1, GL000247.1, HSCHR17_1, HSCHR6_MHC_APD, HSCHR6_MHC_COX, HSCHR6_MHC_DBB, HSCHR6_MHC_MANN, HSCHR6_MHC_MCF, HSCHR6_MHC_QBL, HSCHR6_MHC_SSTO, chrM
#   Make sure to always combine/compare objects based on the same reference
#   genome (use suppressWarnings() to suppress this warning).

save(rse, file="Annotated.Rdata")

## QC
load("ZhangkunAnnotated.Rdata")
colnames(colData(rse)) <- c("cellID")
colData(rse)
# DataFrame with 1047 rows and 1 column
#            cellID
#          <factor>
# 1    ACTTTCTAATCA
# 2    GAGAGAAAACCT
# 3    TACGGCTGTTAT
rowRanges(rse)
# GRanges object with 136475 ranges and 4 metadata columns:
#            seqnames                 ranges strand |    DHSsum distanceToTSS
#               <Rle>              <IRanges>  <Rle> | <numeric>     <numeric>
#        [1]     chr2 [149639224, 149639496]      * |  7.181268          3932
#        [2]     chr8 [100508027, 100508251]      * | 13.309979        -32028
#        [3]    chr22 [ 22089734,  22090705]      * | 29.947934           389
#        [4]     chr3 [ 28282796,  28283506]      * | 41.063828          -280
#        [5]     chr5 [154007199, 154007946]      * |  8.373110        -58138
#        ...      ...                    ...    ... .       ...           ...
#   [136471]    chr15   [76102342, 76102770]      * | 25.272808         11936
#   [136472]    chr15   [76546242, 76546617]      * |  5.719444         46920
#   [136473]    chr15   [77097573, 77097864]      * | 18.791629         43682
#   [136474]    chr15   [78177410, 78177781]      * | 31.069898         30858
#   [136475]    chr15   [79471519, 79471726]      * | 20.755744        -30612
#                    feature         region
#                <character>    <character>
#        [1] ENSG00000231079 distal element
#        [2] ENSG00000206699 distal element
#        [3] ENSG00000100027       promoter
#        [4] ENSG00000187118       promoter
#        [5] ENSG00000221552 distal element
#        ...             ...            ...
#   [136471] ENSG00000214677 distal element
#   [136472] ENSG00000214679 distal element
#   [136473] ENSG00000245779 distal element
#   [136474] ENSG00000225033 distal element
#   [136475] ENSG00000207695 distal element
#   -------
#   seqinfo: 32 sequences from an unspecified genome; no seqlengths

assay(rse)[1:5,1:5]
# 5 x 5 sparse Matrix of class "dgTMatrix"
# [1,] 1 1 1 . .
# [2,] 1 1 . . .
# [3,] . . . . .
# [4,] . . . . .
# [5,] . . . . .
rse = doQC(rse, regionSumCutoff = 3, cellSumCutoffSDs = 5)

## Determine number of clusters
set.seed(10)
nClustersMax = 10
clusterEst = estimateNClusters(rse, nClustersMax = nClustersMax)
pdf("./plotNClusters.pdf",width=8,height=8)
plotNClusters(clusterEst)
dev.off()

nCores = 2
PCrange = 8:15
TSSWeightsList = list(c(1,1))
DHSWeightsList = list(c(1,1))

nClusters = 4
results = destinGrid (rse, sampleName,
                      PCrange = PCrange,
                      TSSWeightsList = TSSWeightsList,
                      DHSWeightsList = DHSWeightsList,
                      nClusters = nClusters,
                      nCores = nCores)

# Error in `[<-.data.table`(x, j = name, value = value) : 
#   Cannot use := to add columns to a null data.table (no columns), currently. You can use := to add (empty) columns to a 0-row data.table (1 or more empty columns), though.

Many thanks for your help!
Jingxin

**Comment by urrutiag** [comment]
Hi Jingxin,

If you haven't already, please clone and install the latest version of
Destin from github

The parameters of destinGrid have changed.  sampleName is no longer a
parameter.  Use help(destinGrid) for additional info.  All vignettes have
been updated to reflect this change.

Please call destinGrid as so in your case:
results = destinGrid (rse,
PCrange = PCrange,
TSSWeightsList = TSSWeightsList,
DHSWeightsList = DHSWeightsList,
nClusters = nClusters,
nCores = nCores)

As for the warnings in annotateRSE, I don't think they are an issue.  I
don't see warnings when I run with my data, but my seqnames may be
different than yours.
> seqnames(rse)
factor-Rle of length 97824 with 23 runs
  Lengths:  9382  7739  6288  4048  4993  5844 ...  4192  2866  1277  2150
2498
  Values :  chr1  chr2  chr3  chr4  chr5  chr6 ... chr19 chr20 chr21 chr22
chrX
Levels(24): chr1 chr2 chr3 chr4 chr5 chr6 ... chr19 chr20 chr21 chr22 chrX
chrY

Please let me know if you have any other questions

Gene
