### ISSUE TITLE
getDiffAccess question

### ISSUE THREAD

**Issue by jk86754** [urrutiag/destin#4]
Hi,

is it possible to get differential access from comparing cells by something other than cluster assignment? For example, disease vs. healthy, treated vs untreated etc.?

thank you,

Joe

**Comment by urrutiag** [comment]
Hi Joe, great idea, give me a few days to push an update.
Gene

**Comment by urrutiag** [comment]
Pushed update to github
See last step of 'destinBuenrostroMouse.html' for example
Gene

**Comment by jk86754** [comment]
thank you! i will try it with my data today

**Comment by jk86754** [comment]
seems to be working well. Thanks for addressing.
