### ISSUE TITLE
Help with differential accessibility analysis for KO vs. WT

### ISSUE THREAD

**Issue by sharvari14** [urrutiag/destin#5]
Hello,

I have scATAC-Seq data for two conditions - WT and KO, and wondered if Destin tool can be used to perform differential accessibility analysis for KO vs. WT. I have raw data and processed data from cell ranger atac pipeline.

Appreciate all the help.

Thanks
Sharvari

**Comment by yuchaojiang** [comment]
Hi,

Please refer to https://rawgit.com/urrutiag/destin/master/package/vignettes/destinPreisslP56.html#differential-accessibility . Feel free to let us know if you have additional questions.

Yuchao

On Jun 19, 2019, at 10:03 PM, sharvari14 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

I have scATAC-Seq data for two conditions - WT and KO, and wondered if Destin tool can be used to perform differential accessibility analysis for KO vs. WT. I have raw data and processed data from cell ranger atac pipeline.

Appreciate all the help.

Thanks
Sharvari

**Comment by sharvari14** [comment]
Hello Yuchao,

Thank you for the reply and sharing the link.

Looking at section 3.9, it seems to me the the differential accessibility
is between clusters, and not genotypes. Can you please advice if the tool
has functionality to compare changes in the chromatin accessibility for two
genotypes - WT and KO.

Appreciate all the help.
Thanks
Sharvari

**Comment by yuchaojiang** [comment]
Hi Gene,
Can you help? I believe this is easy to add.
Thanks
Yuchao

Sent from my iPhone

On Jun 20, 2019, at 10:34 AM, sharvari14 <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello Yuchao,

Thank you for the reply and sharing the link.

Looking at section 3.9, it seems to me the the differential accessibility
is between clusters, and not genotypes. Can you please advice if the tool
has functionality to compare changes in the chromatin accessibility for two
genotypes - WT and KO.

Appreciate all the help.
Thanks
Sharvari

**Comment by urrutiag** [comment]
Yes, Destin can do this, please see:

https://rawgit.com/urrutiag/destin/master/package/vignettes/destinBuenrostroMouse.html#differential-accessibility

"Alternatively, we can examine differential access on a label such as
disease vs. healthy, treated vs untreated etc."

Thanks,
Gene

**Comment by sharvari14** [comment]
Thanks Gene. That is really helpful to know. Sorry to bother you with a few
more questions.

The experimental design I have for scATAC-Seq is for two conditions - WT
and KO (no replicates) , with alignments and peaks (bed file with three
columns) generated using the cell ranger atac pipeline from 10x Genomics.
Using R Matrix package, I have feature count matrix for each condition - WT
(~1500 cells, 66K peaks) and KO (~2000 cells, 64K peaks)

1. To create the RSE object, do I need to pre-process the data
independently to generate merged peaks file?
2. Is the tool compatible with the peaks file from 10x?
3. How to define 'alternateCellLabel' for data without replicates?

Appreciate your feedback.
Thanks
Sharvari

**Comment by urrutiag** [comment]
1. To create the RSE object, do I need to pre-process the data
independently to generate merged peaks file?
All cells from both KO and WT should be run together to call peaks

2. Is the tool compatible with the peaks file from 10x?
Yes, please see:
https://rawgit.com/urrutiag/destin/master/package/vignettes/10xGenomicsPBMC.html

3. How to define 'alternateCellLabel' for data without replicates?
Replicates is not a requirement.  alternateCellLabel is a vector of labels
with one entry per cell

Thanks,
Gene

**Comment by sharvari14** [comment]
Hi Gene,
Thank you sharing the link. Using 'createRSEfrom10xMatrix' I get a sparse
matrix for each condition.
And so, when you mention calling peaks for both conditions (WT and KO)
together, I am a bit confused. Can you please point me to a paper/tool for
scATAC-Seq to do this?
Thanks again
Sharvari

**Comment by urrutiag** [comment]
The Buenrostro Mouse example contains an end to end bioinformatics pipeline
starting from fastq.  This would be the route to call peaks simultaneously
using Destin.  However, since you used cell ranger to process, you could
instead run through their pipeline with both WT and KO simultaneously, and
achieve the comparable result.

https://rawgit.com/urrutiag/destin/master/package/vignettes/destinBuenrostroMouse.html

Thanks,
Gene

**Comment by sharvari14** [comment]
Hi Gene,

Thank you so much for sharing info on the pipeline. If I understand
correctly, the alignment and peak calling is done for each cell.

The raw sequencing files for each condition are from running
cellranger-atac mkfastq
to demultiplex raw base call (BCL) files that are generated by Illumina
sequencers into FASTQ files.
For ex:
https://support.10xgenomics.com/single-cell-atac/software/pipelines/latest/using/fastq-input

Would you recommend any other option for this scenario?

I am a newbie to scATAC-seq analysis, and apologize for all the questions.
Appreciate your patience and feedback.
Thanks
Shar

**Comment by urrutiag** [comment]
Thank you so much for sharing info on the pipeline. If I understand
correctly, the alignment and peak calling is done for each cell.
- alignment is done for each individual cell
- peak calling is done for all cells combined

The raw sequencing files for each condition are from running
cellranger-atac mkfastq
to demultiplex raw base call (BCL) files that are generated by Illumina
sequencers into FASTQ files.
- Demultiplexing is non-standard, and I would recommend using the above
method or another if recommended by Illumina according to their protocol.
Destin assumes cells have already been demultiplexed.
