### ISSUE TITLE
aggregateRSEByGene error for human data

### ISSUE THREAD

**Issue by tintin306** [urrutiag/destin#6]
I have human scATACseq data, so I didn't run  annotateMouseToHuman and just ran directly:

se = aggregateRSEByGene(rse)
Error in assaysList[[1]] : subscript out of bounds
It seems the error occurs because there is no entrez column in metadata.

Thanks,

**Comment by nes-b** [comment]
Same here.
It seems like there is some EntrezID matching problem, also when using ensembldb package.
The function then appears to get stuck with NAs in the rse subsetting part in the first sub-function called 'aggregateGene'. 

This seems to be a similar error in other (R)SE-based functions
see #https://github.com/satijalab/seurat/issues/1791

Hope, to get some suggestion, please.

Thank you,
nes

**Comment by urrutiag** [comment]
Thanks all. I will look into this.  Best, Gene

**Comment by urrutiag** [comment]
tintin,
Thank you for your comments. We want to ensure that Destin can accomodate GWAS for human scATAC-seq experiments.  I have added the annotateHuman() function to add the entrez_id.  see help(annotateHuman) for a usage example. Please pull latest from github and let me know if you need anything else.
Best, Gene

nes,
Gene mapping is not the focus of Destin, and relies on ChIPpeakAnno. Destin drops ranges that are not mapped to entrezID prior to GWAS analysis.  I have added this functionality to the human scATAC-seq workflow as well for compatibility. Please pull latest from github and let me know if you need anything else.
Best, Gene

**Comment by tintin306** [comment]
Thank you
